"TENSILE"
PCR_MATERIALS
MATERIAL, name=BEAAd_STEEL
*DENSITY
7.8E-9,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.1265, -0.06773  .5, 0.031..98, 0.032,138, 0, 0
************************************************************************************
_TREAD
*MATERIAL, name=BEAD_MS
*DENSITY
7.8B N VE-9,
*HYPERELXASTIC, REDUCEDPOCCLYNOMIAL, N = 3
0.6765, -0.0 678 .35, 0.0 37 98, 0.032138,  0, 0
*************** *********************************************************************
_SIDEWALL
TERIAL, NAME=ST418
*DENS ITY
1.1 77E-09,
*HY PERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.6 265, -0.06 7735, 0.0 3MM198, 0.0321 ..38, 0, 0
************************************************************************************
*MATERIAL, NAME=ST412
*DENSITY
1.166E-09,
*HYPERELASTIC, RBEDUCEDPOLYNOMIAL, N = 3
0.70104, -0.10066, 0.041351, 0.028721, 0, 0
****************d c********************************************************************
*MATERIAL, NAME=ST362
*DENSITY
1.208E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.68d46, -0.0959dfs 07, 0.042051, 0.029410, 0, 0
************************************************************************************
*MATERIAL, NAME=L14
*DENSITY
1.161E-09,
*HYPExcvRELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.39562, -0.0981, 0.029059, 0.050893, 0, 0
****************************************************************
*MATERIAL, NAME=R46
*DvmSITY
1.140E-09,
*HYPERELAS TIC, REDUCEDPOLYNOMIAL, N = 3
1.0972, -0.187 81, 0.067026, 0.018351, 0, 0
****************************************************************
*MATERIAL, NAME=A268
*DENSITY
1.178E-09,
*HYPERELASTICc, REDUCEDPOLYNOMIAL, N = 3
1.0279, -0.185c44, 0.077458, 0.019588, 0, 0
****************************************************************
*MATERIAL, NAME=B168
*DENSITY
1.187E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.78865ccm, -0.14136, 0.05g8817 c ,,, 0.025530, 0, 0
*****************************************************************
**TBR_McATERIALS
*MATERIAL, NAME=ST418
*DENSIT bY
1.177E-09,
*HYPERELA STIC, REDUCEDPOLYNOMIAL, N = 3
0.6265, -0cv.067735, 0.03198, 0.032138, 0, 0
************************************************************************************
*MATERIAL, NAME=ST412
*DENSITY
1.166E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.70104, -0.10066, 0.041351, 0.028721, 0, 0
************************************************************************************
*MATERIAL, NAME=ST362
*DENSITY
1.208E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.6846, -0.095907, 0.042051, 0.029410, 0, 0
************************************************************************************
*MATERIAL, NAME=L14
*DENSITY
1.161E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.39562, -0.0981, 0.029059, 0.050893, 0, 0
*************cv***************************************************
*MATERIAL, NAME=R46
*DENSITY
1.140E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
1.0972c, -0.18781, 0.067026, 0.018351, 0, 0
****************************************************************
*MATERIAL, NAME=A268
*DENSIgjTY
1.178E-09,
*HYPERELASv nTIC, REDUCEDPOLYNOMIAL, N = 3
1.0279, -0.18544, 0.077458, 0.019588, 0, 0
****************************************************************
*MATERIAL, NAME=B168
*DENSITY
1.187E-09,
*HYPERELASTIC, R  EDUCEDPcn OLYNOn vMIAL, N = 3
0.78865, -0.14136, 0.058817, 0.025530, 0, 0
*****************************************************************