"DMA"
**PCR_MATERIALS
_TREAD
*MATERIAL, NAME=ST100
*DENSITY
1.177E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 2
0.35, -0.05, 0.02, 0.01
************************************************************************************
*MATERIAL, NAME=IL200
*DENSITY
1.161E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 3
0.4, -0.06, 0.03, 0.015, 0, 0
************************************************************************************
**TBR_MATERIALS
_BELT
*MATERIAL, NAME=BT500
*DENSITY
1.190E-09,
*HYPERELASTIC, REDUCEDPOLYNOMIAL, N = 1
0.6, 0.04
************************************************************************************
